web/sysgate/account/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='reset'),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password_change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^registro/$', views.registro, name='registro'),
]

web/sysgate/apps/core/urls.py
from django.conf.urls import url

from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
]

web/sysgate/apps/metrics/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register(r'metricas', views.MetricasViewSet, 'metricas')

app_name = 'metrics'

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^api/v1/', include(router.urls)),
]

web/sysgate/urls.py
"""
SYSGATE URL Configuration
"""
from django.conf import settings
from django.conf.urls import (handler400, handler403, handler404, handler500,
                              include, url)
from django.contrib import admin
from sysgate.apps.core.views import error_400, error_403, error_404, error_500

handler400 = error_400
handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = [
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^account/', include('account.urls'), name='Autenticación'),
    url(r'^metrics/', include('apps.metrics.urls'), name='Métricas'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += staticfiles_urlpatterns()

web/sysgate/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#user-model
    """

    direccion1 = models.CharField(max_length=50, null=True, blank=True)
    direccion2 = models.CharField(max_length=50, null=True, blank=True)
    ciudad = models.CharField(max_length=50, null=True, blank=True)
    provincia = models.CharField(max_length=50, null=True, blank=True)
    telefono = models.CharField(max_length=32, null=True, blank=True)

web/sysgate/apps/metrics/models.py
from django.db import models
from django.utils.timezone import now


class Metrica(models.Model):
    nombre = models.CharField(primary_key=True, max_length=30)
    TIPO = (
        ('c', 'Custom'),
        ('d', 'Disk'),
        ('p', 'CPU'),
        ('n', 'Network'),
    )
    tipo = models.CharField(max_length=1, choices=TIPO, default='c')
    alta = models.DateTimeField(auto_now_add=True, editable=False)
    modificacion = models.DateTimeField(default=now, blank=False)
    descripcion = models.TextField(max_length=300, blank=True)

    class Meta:
        verbose_name = 'Métrica'
        verbose_name_plural = 'Métricas'

web/sysgate/account/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import forms as django_forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class LoginForm(django_forms.AuthenticationForm):
    username = forms.CharField(
        label='Usuario', max_length=20)

    def __init__(self, request=None, *args, **kwargs):
        super(LoginForm, self).__init__(request=request, *args, **kwargs)
        if request:
            username = request.GET.get('username')
            if username:
                self.fields['username'].initial = username


class RegistroForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Debe ser valído')

    def __init__(self, *args, **kwargs):
        """Initiate form with Crispy Form's FormHelper."""
        super(RegistroForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        # Add 'Submit' button
        self.helper.add_input(Submit('submit', 'Registrar'))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

web/sysgate/account/views.py
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth import login as login_auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as login_view
from django.shortcuts import redirect, render
from django.template.response import TemplateResponse
from django.views.generic import View

from .forms import LoginForm, RegistroForm
from .models import User


def login(request):
    kwargs = {
        'template_name': 'account/login.html',
        'authentication_form': LoginForm}
    return login_view(request,
                        extra_context={'site_name': settings.SITE_NAME,
                                       'title': 'Autenticación'},
                        **kwargs)

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, 'Usuario desconectado.')
    return redirect(settings.LOGIN_REDIRECT_URL)

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'])
            login_auth(request, new_user)
            messages.info(request, 'Gracias por registrarse. Sesión abierta')
            return redirect(settings.LOGIN_REDIRECT_URL)
    else:
        form = RegistroForm()
    return render(request, 'account/registro.html', {'form': form})


@login_required
def profile(request):
    ctx = {'usuario': User.objects.get(id=request.user.id)}
    return TemplateResponse(request, 'account/profile.html', ctx)

web/sysgate/apps/core/views.py
from django.shortcuts import render
from django.views.defaults import (bad_request, page_not_found,
                                   permission_denied, server_error)
from django.views.generic import View


def error_400(request, exception):
    return bad_request(request, exception)


def error_403(request, exception):
    return permission_denied(request, exception)


def error_404(request, exception):
    return page_not_found(request, exception)


def error_500(request):
    return server_error(request)

class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/home.html')

web/sysgate/apps/metrics/views.py
import requests

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.permissions import IsAuthenticated
from sysgate.apps.core.permissions import (EsSuperOTienePermisosPorGrupo,
                                           super_o_esta_en_grupo)

from .models import Metrica
from .serializers import SerializerMetricas


@method_decorator(login_required, name='dispatch')
class Home(UserPassesTestMixin, View):
    def test_func(self):
        return super_o_esta_en_grupo(self.request.user, grupo='pycones_gr')

    def get(self, request, *args, **kwargs):
        r = requests.get('http://sysgate:8000/metrics/api/v1/metricas/')
        return render(request,
                      'metrics/home.html',
                      context={'metricas': r.json()})

class MetricasViewSet(viewsets.ModelViewSet):
    grupos_autorizados = settings.GR_AUTH_METRICS
    permission_classes = (IsAuthenticated, EsSuperOTienePermisosPorGrupo,)
    serializer_class = SerializerMetricas
    http_method_names = ['get']
    filter_backends = (OrderingFilter, SearchFilter,)
    search_fields = ('tipo',)

    def get_queryset(self):
        queryset = Metrica.objects.all().order_by('tipo')
        tipo = self.request.query_params.get('tipo', None)

        if tipo is not None:
            queryset = queryset.filter(tipo=tipo)

        return queryset

web/sysgate/apps/core/templates/core/home.html
{% extends 'base.html' %}

{% load core_tags %}

{% block content %}

<div class="container">
  <img src="/static/img/logo_pycones17.png" class="center-block">
  <br>

  {% if request.user|en_grupo:"pycones_gr" or user.is_superuser %}
    <div class="jumbotron container-fluid">
     <h1>Métricas</h1>
      <p><a class="btn btn-lg btn-success" href="{% url 'metrics:home' %}" role="button">Acceder</a></p>
    </div>
  {% endif %}

  {% if not user.is_authenticated %}
    <div class="alert alert-warning alert-dismissable col-md-6 col-md-offset-3" align="center" role="alert">
      <i class="fa fa-info-circle" aria-hidden="true"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      Inicie sesión para acceder al Dashboard
    </div>
  {% elif request.user|sin_grupos and not user.is_superuser %}
    <div class="alert alert-danger col-md-6 col-md-offset-3" align="center" role="alert">
      <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
      <strong>No existen aplicaciones registradas a su Usuario</strong>
    </div>
  {% endif %}
</div>

{% endblock %}

web/sysgate/apps/metrics/templates/metrics/home.html
{% extends 'base.html' %}

{% load static %}

{% block extrajs %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js"></script>
{% endblock %}

{% block content %}

<div id="container" class="container">
  <table>
    <thead>
      <tr>
        <th>Métrica</th>
        <th>Tipo</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="metrica in metricas">
        <td>[[ metrica.nombre ]]</td>
        <td>[[ metrica.long_tipo ]]</td>
      </tr>
    </tbody>
  </table>
</div>

<script>
  var v = new Vue({
    delimiters: ['[[', ']]'],
    el: '#container',
    data: {
      metricas: []
    },
    mounted: function(){
      $.get('/metrics/api/v1/metricas/', function(data){
        v.metricas = data;
      })}
  })
</script>

{% endblock content %}

web/sysgate/templates/base.html
{% extends 'base_generic.html' %}


{% block content %}{% endblock %}

web/sysgate/templates/base_generic.html
{% load i18n static %}
<!DOCTYPE html>
<link rel="shortcut icon" type="image/png" href="{% static "img/favicon.ico" %}"/>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"es-es" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>SysGate</title>
<!-- Fuentes -->
<link href="https://fonts.googleapis.com/css?family=Lora|Open+Sans|Rubik" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<!-- JS -->
<script
src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block extrajs %}{% endblock %}
<!-- CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-custom navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button"
                  class="navbar-toggle collapsed"
                  data-toggle="collapse"
                  data-target="#navbar"
                  aria-expanded="false"
                  aria-controls="navbar">
            <span class="sr-only">Desactivar Navegación</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" rel="home" href="{% url 'core:home' %}" title="SysGate">SysGate</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-left">
            <li class=" dropdown"><a href="#"
                                     class="dropdown-toggle active"
                                     data-toggle="dropdown"
                                     role="button"
                                     aria-haspopup="true"
                                     aria-expanded="false">
                                     Acerca de
                                     <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="https://github.com/klashxx/PyConES2017/">GitHub</a></li>
                    <li><a href="https://klashxx.github.io/slides/django/#/">Slides</a></li>
                    <li><a href="https://klashxx.github.io/about">Contacto</a></li>
                </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li class=" dropdown"><a href="#"
                                             class="dropdown-toggle active"
                                             data-toggle="dropdown"
                                             role="button"
                                             aria-haspopup="true"
                                             aria-expanded="false">
                                             {% firstof user.get_short_name user.get_username %}
                                             <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                              <li class=""><a href="{% url 'admin:index' %}">Administración</a></li>
                            {% endif %}
                            <li><a href="{% url 'account:profile' %}">Mi Cuenta</a></li>
                        </ul>
                    </li>
                {% endif %}
                {% if not user.is_authenticated %}
                  <li class="">
                    <a href="{% url 'account:login' %}" aria-label="Login usuario">
                      <i class="fa fa-user-o fa-2x" aria-hidden="true"></i>
                    </a>
                  </li>
                {% else %}
                  <li class="">
                    <a href="{% url 'account:logout' %}" aria-label="Logout usuario">
                      <i class="fa fa-power-off fa-2x" aria-hidden="true"></i>
                    </a>
                  </li>
                {% endif %}
            </ul>
        </div>
      </div>
    </nav>

    {% block breadcrumb %}
    <div class="container">
        <div class="row">
            <div class="btn-group btn-breadcrumb">
                <a href="{% url 'core:home' %}"
                   class="btn btn-default">
                   <i class="glyphicon glyphicon-home"></i>
                </a>
                  {% for bread in breads %}
                    <a href="{{ bread.full_path }}" class="btn btn-default">&nbsp;{{ bread.path }}</a>
                  {% endfor %}

            </div>
        </div>
    </div>
    {% endblock breadcrumb %}

   {% block messages %}
       {% if messages %}
          <div class="container">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable fade in col-md-6 col-md-offset-3" align="center" role="alert">
            <i class="fa fa-info-circle" aria-hidden="true"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message|capfirst }}
            </div>
          {% endfor %}
          </div>
       {% endif %}
   {% endblock messages %}

   <!-- Content -->
   <div id="content" class="{% block coltype %}colM{% endblock %}">

       {% block pretitle %}{% endblock %}
       {% block content_title %}{% endblock %}
       {% block content %}
       {% block object-tools %}{% endblock %}
       {{ content }}
       {% endblock %}
       {% block sidebar %}{% endblock %}
       <br class="clear" />
   </div>
   <!-- END Content -->
   {% block footer %}
   <footer class="footer">
     <div class="container">
       <p class="text-muted" style="margin-top: 10px;">PyConES, Cáceres 2017</p>
     </div>
   </footer>
   {% endblock %}

</body>
</html>